### ISSUE TITLE
Low Zoom heavily breaks website

### ISSUE THREAD

**Issue by leonzalion** [abstractultra/eoBlog#17]
![Screen Shot 2019-07-11 at 12 19 26 AM](https://user-images.githubusercontent.com/36966635/61021981-af592e00-a371-11e9-8877-fe87eab656c5.png)
More funny than actually a legitimate problem. Treat this issue how you want lol

**Comment by abstractultra** [comment]
The issue in this case would be the small font size which is unreadable.

**Comment by abstractultra** [comment]
Also, I am unable to replicate this issue.
