### ISSUE TITLE
Sidebar activator much tinier on Firefox

### ISSUE THREAD

**Issue by leonzalion** [abstractultra/eoBlog#19]
![Screen Shot 2019-07-11 at 12 32 07 AM](https://user-images.githubusercontent.com/36966635/61022331-5f7b6680-a373-11e9-87c3-1018b8220d2c.png)

**Comment by abstractultra** [comment]
I don't believe I have ever tested the site in Chrome. The issue here is that the activator is bigger than I expected in Chrome, although I don't consider this to be a bug. All browsers will display some things differently.
